import './js/fetch-movies';
import './js/search-movies';
import './js/pagination';
import './js/film-card-modal';
// import './js/button-top';
// import './js/students';
import './js/modal-team';
import './js/to-top-button';
import './js/get-trailers';
import './js/firebase';
